version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: chat_db
    ports:
      - "3307:3306"  # Change host port to 3307

  app:
    build: .
    container_name: user-chat-app
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "8080:8080"



